apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.general.namespace }}
  labels:
    app: {{ .Values.deployment.app_name }}
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.ruby_port }}
    targetPort: {{ .Values.service.ruby_port }}
  selector:
    app: {{ .Values.deployment.app_name }}