name: Deploy to Kubernetes

on: 
  workflow_dispatch:

env:
  REGISTRY: "viktillo"
  IMAGE_NAME: "valentin-mum-api"

jobs:
  # push_to_registry:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: viktillo/valentin-mum-api:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: push_to_registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 valentin-mum-api && cat /home/runner/.kube/config
      
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.14.3' # default is latest stable
        id: install

      - name: Run Helm upgrade
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade valentin-mum-api kubernetes/ -f kubernetes/values.yaml
          kubeconfig: '/home/runner/.kube/config'
          



