name: Run Rubocop
on: [push]
jobs:
  run-rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop --config .rubocop.yml